- hosts: localhost
  vars:
    lan1: 
      address: 192.168.1.241
      ipam:
        subnet: 192.168.1.0/24
        gateway: 192.168.1.1
        ip_range: 192.168.1.240/29
    lan2: 
      address: null
      ipam: null
  tasks:
  - name: Import Docker group
    import_tasks: task_groups/docker.yml
    tags:
    - docker
  - name: Import fixes
    import_tasks: task_groups/fixes.yml
  - name: Import Compose group
    import_tasks: task_groups/compose.yml
    tags:
    - compose

