- hosts: localhost
  vars:
    lan1: 
      address: 192.168.1.241
      ipam:
        subnet: 192.168.1.0/24
        gateway: 192.168.1.1
        ip_range: 192.168.1.240/29
    lan2: 
      address: null
      ipam: null
  tasks:
  - name: Install docker
    shell:
      cmd: `armbian-config --CON001`
    tags:
    - never
    - install
  - name: Udev fix
    lineinfile:
      ## On my system, after first reboot lan2 switched
      #  from 0001:01:00.0 to 0001:11:00.0 ; 
      #  Not sure why and it may not happen to you, so this is a manual task
      path: /etc/udev/rules.d/70-persistent-net.rules
      regexp: '^SUBSYSTEM.*lan2"'
      line: 'SUBSYSTEM=="net", ACTION=="add", KERNELS=="0001:11:00.0", NAME:="lan2"'
      state: present
    tags:
    - never
    - manual
  - name: Import Compose group
    import_tasks: task_groups/compose.yml
    tags:
    - compose

